import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, PrimaryButton, Progress } from "../../../components/UI";

const subnav=[{label:"Intelligence ticket",href:"/service-ops"},{label:"Charge & capacité",href:"/service-ops/workload"},{label:"Connaissances",href:"/service-ops/knowledge",active:true},{label:"Actions IA",href:"/service-ops/actions"}];

export default function KnowledgePage(){return <AppShell section="service" subnav={subnav} searchPlaceholder="Rechercher dans les connaissances..."><PageIntro eyebrow={<span className="eyebrow tone-blue">Intelligence documentaire</span>} title="Intelligence des connaissances" subtitle="Mesurer la qualité du RAG, détecter les lacunes documentaires et transformer les résolutions récurrentes en articles gouvernés." action={<PrimaryButton><span className="material-symbols-outlined">auto_awesome</span>Générer un brouillon</PrimaryButton>}/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Couverture documentaire</span><span className="material-symbols-outlined green">library_books</span></div><div className="metric-value green">87 %</div><div className="metric-note">+4,2 % SUR 30 JOURS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Réponses RAG sourcées</span><span className="material-symbols-outlined blue">link</span></div><div className="metric-value blue">94,1 %</div><div className="metric-note">JEU DE RÉFÉRENCE · 560 REQUÊTES</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Lacunes documentaires</span><span className="material-symbols-outlined amber">warning</span></div><div className="metric-value amber">12</div><div className="metric-note">4 SUJETS À FORT IMPACT</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Articles à revoir</span><span className="material-symbols-outlined red">history</span></div><div className="metric-value red">18</div><div className="metric-note">REVUE &gt; 180 JOURS</div></GlassCard>
<GlassCard className="card-pad span-7"><div className="card-header"><h3><span className="material-symbols-outlined amber">psychology_alt</span>Détection des lacunes documentaires</h3><Chip tone="amber">À traiter en priorité</Chip></div>{[["Renouvellement du certificat VPN après remplacement du poste","34 résolutions similaires","Aucun article validé","96 %"],["Réinitialisation du jeton M365 après synchronisation du mot de passe","27 résolutions similaires","Article partiel uniquement","91 %"],["Redirection d’imprimante Citrix en session partagée","19 résolutions similaires","Aucun article","88 %"],["Instabilité du roaming des scanners en entrepôt","16 résolutions similaires","Procédure obsolète","84 %"]].map(r=><div className="action-card" key={r[0]}><div className="action-head"><strong>{r[0]}</strong><span className="green mono">{r[3]}</span></div><p>{r[1]} · {r[2]}</p><div className="action-meta"><span>Action proposée : générer un brouillon</span><span>Responsable : Knowledge Manager</span></div></div>)}</GlassCard>
<GlassCard className="card-pad span-5"><div className="card-header"><h3><span className="material-symbols-outlined blue">hub</span>Fiabilité des sources</h3></div>{[["Base de connaissances Freshservice validée",98,"green"],["Référentiel de procédures internes",92,"green"],["Résolutions historiques de tickets",81,"blue"],["Notes privées des agents",54,"amber"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "green"|"blue"|"amber"}/></div>)}<div className="action-card"><span className="card-label">Politique de recherche</span><p>Seules les sources autorisées par les droits du workspace et les seuils de confiance sont envoyées dans le contexte de génération.</p><Chip tone="green">RAG gouverné</Chip></div></GlassCard>
<GlassCard className="table-card span-12"><div className="card-pad"><div className="card-header"><h3><span className="material-symbols-outlined green">description</span>Cycle de vie des articles</h3><Chip tone="muted">Validation humaine requise</Chip></div></div><div className="table-head cols-6"><span>Article</span><span>Origine</span><span>Pertinence</span><span>État</span><span>Responsable</span><span>Prochaine étape</span></div>{[["Renouvellement certificat VPN","34 tickets","96 %","Brouillon prêt","Workplace N2","Relire"],["Invalidation du cache IAM","28 tickets","93 %","Validé","Équipe Identité","Publier"],["Procédure redirection imprimante","19 tickets","88 %","Expert requis","Workplace","Enrichir"],["Roaming terminaux M3","16 tickets","84 %","Obsolète","Mobilité","Réécrire"]].map(r=><div className="table-row cols-6" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className="blue">{r[2]}</span><Chip tone={r[3]==="Validé"?"green":r[3]==="Obsolète"?"red":"amber"}>{r[3]}</Chip><span>{r[4]}</span><span className="green mono">{r[5]} →</span></div>)}</GlassCard>
</div></AppShell>}
