import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, PrimaryButton, Progress } from "../../../components/UI";
const subnav=[{label:"Ticket Intelligence",href:"/service-ops"},{label:"Workload & Capacity",href:"/service-ops/workload"},{label:"Knowledge",href:"/service-ops/knowledge",active:true},{label:"AI Actions",href:"/service-ops/actions"}];
export default function KnowledgePage(){return <AppShell section="service" subnav={subnav} searchPlaceholder="Search semantic knowledge..."><PageIntro eyebrow={<span className="eyebrow tone-blue">Semantic Knowledge Fabric</span>} title="Knowledge Intelligence" subtitle="Measure RAG health, find knowledge gaps and turn repeated resolutions into governed articles." action={<PrimaryButton><span className="material-symbols-outlined">auto_awesome</span>Generate Draft</PrimaryButton>}/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Knowledge Coverage</span><span className="material-symbols-outlined green">library_books</span></div><div className="metric-value green">87%</div><div className="metric-note">+4.2% LAST 30 DAYS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">RAG Grounding</span><span className="material-symbols-outlined blue">link</span></div><div className="metric-value blue">94.1%</div><div className="metric-note">GOLDEN SET · 560 QUERIES</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Knowledge Gaps</span><span className="material-symbols-outlined amber">warning</span></div><div className="metric-value amber">12</div><div className="metric-note">4 HIGH IMPACT TOPICS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Stale Articles</span><span className="material-symbols-outlined red">history</span></div><div className="metric-value red">18</div><div className="metric-note">REVIEW WINDOW &gt; 180 DAYS</div></GlassCard>
<GlassCard className="card-pad span-7"><div className="card-header"><h3><span className="material-symbols-outlined amber">psychology_alt</span>Knowledge Gap Detector</h3><Chip tone="amber">Priority Queue</Chip></div>{[["VPN certificate renewal after device replacement","34 repeated resolutions","No validated article","96%"],["M365 token reset after password synchronization","27 repeated resolutions","Partial KB only","91%"],["Citrix printer redirection on shared sessions","19 repeated resolutions","No article","88%"],["Warehouse scanner roaming instability","16 repeated resolutions","Outdated SOP","84%"]].map(r=><div className="action-card" key={r[0]}><div className="action-head"><strong>{r[0]}</strong><span className="green mono">{r[3]}</span></div><p>{r[1]} · {r[2]}</p><div className="action-meta"><span>Suggested action: draft article</span><span>Owner: Knowledge Manager</span></div></div>)}</GlassCard>
<GlassCard className="card-pad span-5"><div className="card-header"><h3><span className="material-symbols-outlined blue">hub</span>Source Trust</h3></div>{[["Validated Freshservice KB",98,"green"],["Internal SOP repository",92,"green"],["Resolved ticket patterns",81,"blue"],["Agent private notes",54,"amber"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "green"|"blue"|"amber"}/></div>)}<div className="action-card"><span className="card-label">Retrieval Policy</span><p>Only sources allowed by workspace permissions and trust thresholds are sent into the generation context.</p><Chip tone="green">Governed RAG</Chip></div></GlassCard>
<GlassCard className="table-card span-12"><div className="card-pad"><div className="card-header"><h3><span className="material-symbols-outlined green">description</span>Draft & Article Lifecycle</h3><Chip tone="muted">Human Validation Required</Chip></div></div><div className="table-head cols-6"><span>Article</span><span>Source Pattern</span><span>Relevance</span><span>Status</span><span>Owner</span><span>Next Step</span></div>{[["VPN certificate renewal","34 tickets","96%","Draft Ready","N2 Workplace","Review"],["IAM cache invalidation","28 tickets","93%","Validated","Identity Team","Publish"],["Printer redirection SOP","19 tickets","88%","Needs Expert","Workplace","Enrich"],["M3 handheld roaming","16 tickets","84%","Stale","Mobility","Rewrite"]].map(r=><div className="table-row cols-6" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className="blue">{r[2]}</span><Chip tone={r[3]==="Validated"?"green":r[3]==="Stale"?"red":"amber"}>{r[3]}</Chip><span>{r[4]}</span><span className="green mono">{r[5]} →</span></div>)}</GlassCard>
</div></AppShell>}
