import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, Progress } from "../../../components/UI";
const subnav=[{label:"Ticket Intelligence",href:"/service-ops"},{label:"Workload & Capacity",href:"/service-ops/workload"},{label:"Knowledge",href:"/service-ops/knowledge"},{label:"AI Actions",href:"/service-ops/actions",active:true}];
export default function ActionsPage(){return <AppShell section="service" subnav={subnav} searchPlaceholder="Search recommendation or command..."><PageIntro eyebrow={<span className="eyebrow tone-green">Governed Automation</span>} title="AI Actions & Approvals" subtitle="Every proposed action is scored, policy-checked, previewed and auditable before execution."/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Pending Approval</span><span className="material-symbols-outlined amber">approval</span></div><div className="metric-value amber">7</div><div className="metric-note">2 HIGH RISK · 5 MEDIUM</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Auto Executed Today</span><span className="material-symbols-outlined green">bolt</span></div><div className="metric-value green">184</div><div className="metric-note">L3 SAFE ACTIONS ONLY</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Acceptance Rate</span><span className="material-symbols-outlined blue">thumb_up</span></div><div className="metric-value blue">91%</div><div className="metric-note">30-DAY ROLLING</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Rollback Events</span><span className="material-symbols-outlined red">undo</span></div><div className="metric-value red">2</div><div className="metric-note">0.3% OF EXECUTIONS</div></GlassCard>
<GlassCard className="card-pad span-8"><div className="card-header"><h3><span className="material-symbols-outlined amber">pending_actions</span>Approval Queue</h3><Chip tone="amber">Human-in-the-loop</Chip></div>{[["Promote VPN cluster to Problem","High","Incident Radar","88%","47 incidents will be linked"],["Reassign 14 SLA-risk tickets","Medium","Workload Engine","94%","Move from L1 to Workplace"],["Publish IAM rollback article","Medium","Knowledge Intelligence","93%","KB becomes visible to agents"]].map((r,i)=><div className="action-card" key={r[0]}><div className="action-head"><strong>{r[0]}</strong><Chip tone={r[1]==="High"?"red":"amber"}>{r[1]} Risk</Chip></div><p>{r[4]}</p><div className="action-meta"><span>Source: {r[2]}</span><span>Confidence: {r[3]}</span><span>Policy: {i===0?"P-HITL-HIGH":"P-HITL-MED"}</span></div><div className="action-buttons"><button>Inspect</button><button>Reject</button><button className="approve">Approve & Execute</button></div></div>)}</GlassCard>
<GlassCard className="card-pad span-4"><div className="card-header"><h3><span className="material-symbols-outlined green">shield</span>Autonomy Envelope</h3></div><div className="policy-matrix"><div className="policy-cell"><Chip tone="muted">L0</Chip><strong style={{marginTop:10}}>Observe</strong><p>Read-only signals and detections.</p></div><div className="policy-cell"><Chip tone="blue">L1</Chip><strong style={{marginTop:10}}>Recommend</strong><p>AI proposes, no execution.</p></div><div className="policy-cell"><Chip tone="amber">L2</Chip><strong style={{marginTop:10}}>Approve</strong><p>Human validation required.</p></div><div className="policy-cell"><Chip tone="green">L3</Chip><strong style={{marginTop:10}}>Bounded Auto</strong><p>Safe actions under policy.</p></div></div><div className="action-card"><span className="card-label">Global Write Mode</span><p>Freshservice production writes remain disabled until an administrator explicitly enables them.</p><Progress value={0} tone="muted"/></div></GlassCard>
<GlassCard className="card-pad span-12"><div className="card-header"><h3><span className="material-symbols-outlined blue">timeline</span>Execution Timeline</h3><Chip tone="green">Verified State</Chip></div><div className="timeline"><div className="timeline-item"><h4>14:23:04 · Recommendation created</h4><p>SLA Guardian proposed priority adjustment for INC-9942 with 91% confidence.</p></div><div className="timeline-item"><h4>14:23:07 · Policy decision</h4><p>P-HITL-001 required human approval because action affects priority and assignment.</p></div><div className="timeline-item"><h4>14:24:16 · Approved by manager</h4><p>Before/after state captured and command queued through Freshservice Gateway.</p></div><div className="timeline-item"><h4>14:24:18 · Verified</h4><p>Read-after-write confirmed the Freshservice state and immutable audit event was recorded.</p></div></div></GlassCard>
</div></AppShell>}
