import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, Progress } from "../../../components/UI";

const subnav=[{label:"Intelligence ticket",href:"/service-ops"},{label:"Charge & capacité",href:"/service-ops/workload"},{label:"Connaissances",href:"/service-ops/knowledge"},{label:"Actions IA",href:"/service-ops/actions",active:true}];

export default function ActionsPage(){return <AppShell section="service" subnav={subnav} searchPlaceholder="Rechercher une recommandation ou une commande..."><PageIntro eyebrow={<span className="eyebrow tone-green">Automatisation gouvernée</span>} title="Actions IA & validations" subtitle="Chaque action proposée est évaluée, contrôlée par les politiques, prévisualisée et auditable avant son exécution."/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">À valider</span><span className="material-symbols-outlined amber">approval</span></div><div className="metric-value amber">7</div><div className="metric-note">2 RISQUE ÉLEVÉ · 5 MOYEN</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Exécutées automatiquement aujourd’hui</span><span className="material-symbols-outlined green">bolt</span></div><div className="metric-value green">184</div><div className="metric-note">ACTIONS L3 SÛRES UNIQUEMENT</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Taux d’acceptation</span><span className="material-symbols-outlined blue">thumb_up</span></div><div className="metric-value blue">91 %</div><div className="metric-note">MOYENNE GLISSANTE 30 JOURS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Retours arrière</span><span className="material-symbols-outlined red">undo</span></div><div className="metric-value red">2</div><div className="metric-note">0,3 % DES EXÉCUTIONS</div></GlassCard>
<GlassCard className="card-pad span-8"><div className="card-header"><h3><span className="material-symbols-outlined amber">pending_actions</span>File de validation</h3><Chip tone="amber">Validation humaine</Chip></div>{[["Créer un problème pour le cluster VPN","Élevé","Radar d’incidents","88 %","47 incidents seront liés"],["Réaffecter 14 tickets à risque SLA","Moyen","Moteur de charge","94 %","Transfert du N1 vers Workplace"],["Publier l’article de rollback IAM","Moyen","Intelligence des connaissances","93 %","L’article devient visible aux agents"]].map((r,i)=><div className="action-card" key={r[0]}><div className="action-head"><strong>{r[0]}</strong><Chip tone={r[1]==="Élevé"?"red":"amber"}>Risque {r[1].toLowerCase()}</Chip></div><p>{r[4]}</p><div className="action-meta"><span>Source : {r[2]}</span><span>Confiance : {r[3]}</span><span>Politique : {i===0?"P-HITL-HIGH":"P-HITL-MED"}</span></div><div className="action-buttons"><button>Examiner</button><button>Refuser</button><button className="approve">Valider et exécuter</button></div></div>)}</GlassCard>
<GlassCard className="card-pad span-4"><div className="card-header"><h3><span className="material-symbols-outlined green">shield</span>Niveaux d’autonomie</h3></div><div className="policy-matrix"><div className="policy-cell"><Chip tone="muted">L0</Chip><strong style={{marginTop:10}}>Observation</strong><p>Lecture seule, signaux et détections.</p></div><div className="policy-cell"><Chip tone="blue">L1</Chip><strong style={{marginTop:10}}>Recommandation</strong><p>L’IA propose, aucune exécution.</p></div><div className="policy-cell"><Chip tone="amber">L2</Chip><strong style={{marginTop:10}}>Validation</strong><p>Validation humaine obligatoire.</p></div><div className="policy-cell"><Chip tone="green">L3</Chip><strong style={{marginTop:10}}>Automatisation encadrée</strong><p>Actions sûres autorisées par politique.</p></div></div><div className="action-card"><span className="card-label">Écriture Freshservice</span><p>Les écritures sur la production restent désactivées tant qu’un administrateur ne les active pas explicitement.</p><Progress value={0} tone="muted"/></div></GlassCard>
<GlassCard className="card-pad span-12"><div className="card-header"><h3><span className="material-symbols-outlined blue">timeline</span>Journal d’exécution</h3><Chip tone="green">État vérifié</Chip></div><div className="timeline"><div className="timeline-item"><h4>14:23:04 · Recommandation créée</h4><p>SLA Guardian propose un ajustement de priorité pour INC-9942 avec 91 % de confiance.</p></div><div className="timeline-item"><h4>14:23:07 · Décision de politique</h4><p>P-HITL-001 impose une validation humaine car l’action modifie la priorité et l’affectation.</p></div><div className="timeline-item"><h4>14:24:16 · Validation du manager</h4><p>L’état avant/après est enregistré et la commande est mise en file via le Freshservice Gateway.</p></div><div className="timeline-item"><h4>14:24:18 · Vérification terminée</h4><p>La relecture confirme l’état Freshservice et l’événement d’audit est enregistré.</p></div></div></GlassCard>
</div></AppShell>}
