import { AppShell } from "../../components/AppShell";
import { Chip, GlassCard, PageIntro, Progress } from "../../components/UI";

const subnav = [
  { label: "Intelligence prédictive", href: "/neural-analytics", active: true },
  { label: "Pilotage des modèles", href: "/neural-analytics/models" },
];

export default function NeuralAnalyticsPage() {
  return (
    <AppShell section="neural" subnav={subnav}>
      <PageIntro eyebrow={<span className="eyebrow tone-blue">Signaux prédictifs</span>} title="Intelligence prédictive" subtitle="Anticiper les risques SLA, la pression d’anomalie et la confiance des décisions avant la dégradation du service." />
      <div className="dashboard-grid">
        <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Santé du modèle SLA</span><span className="material-symbols-outlined green">verified</span></div><div className="metric-value green">96,8 %</div><div className="metric-note">CALIBRÉ · v3.4.1</div></GlassCard>
        <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Horizon de prévision</span><span className="material-symbols-outlined blue">schedule</span></div><div className="metric-value blue">12 h</div><div className="metric-note">FENÊTRE GLISSANTE · MAJ 5 MIN</div></GlassCard>
        <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Pression d’anomalie</span><span className="material-symbols-outlined amber">crisis_alert</span></div><div className="metric-value amber">0,73</div><div className="metric-note">ÉLEVÉE · VPN / IAM</div></GlassCard>
        <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Taux d’abstention</span><span className="material-symbols-outlined muted">do_not_disturb_on</span></div><div className="metric-value">7,2 %</div><div className="metric-note">REPLI SÛR ACTIVÉ</div></GlassCard>
        <GlassCard className="big-chart span-8"><div className="card-header"><h3><span className="material-symbols-outlined blue">insights</span>Prévision du risque SLA</h3><Chip tone="blue">Fenêtre de prévision : 12 h</Chip></div><div className="svg-chart"><svg viewBox="0 0 760 260" preserveAspectRatio="none"><defs><linearGradient id="blueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#00e0ff" stopOpacity=".22"/><stop offset="1" stopColor="#00e0ff" stopOpacity="0"/></linearGradient></defs><path d="M0 204 C80 192 112 166 168 172 C231 178 260 131 321 139 C386 147 420 92 482 103 C554 116 585 65 642 75 C699 85 719 44 760 34 L760 260 L0 260 Z" fill="url(#blueFill)"/><path d="M0 204 C80 192 112 166 168 172 C231 178 260 131 321 139 C386 147 420 92 482 103 C554 116 585 65 642 75 C699 85 719 44 760 34" fill="none" stroke="#00e0ff" strokeWidth="4"/><path d="M0 224 C95 215 138 205 190 207 C250 209 309 198 356 201 C430 207 493 178 546 186 C611 196 675 168 760 162" fill="none" stroke="#70f3b8" strokeWidth="2" strokeDasharray="7 7" opacity=".8"/></svg></div></GlassCard>
        <GlassCard className="card-pad span-4"><div className="card-header"><h3><span className="material-symbols-outlined green">psychology</span>Consensus des modèles</h3></div>{[["Gradient Boost SLA",94,"green"],["Transformer temporel",89,"blue"],["Règles métier",72,"amber"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "green"|"blue"|"amber"}/></div>)}<div className="action-card"><span className="card-label">Décision</span><p>Le consensus soutient une réaffectation proactive de 14 tickets. Une validation humaine reste obligatoire.</p><Chip tone="green">Politique : L2</Chip></div></GlassCard>
        <GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined amber">ssid_chart</span>Signaux de dérive</h3><Chip tone="amber">2 éléments à surveiller</Chip></div><div className="source-row"><strong>Répartition de la charge par groupe</strong><span className="amber">+18,4 %</span><span className="muted">écart 7 j</span></div><div className="source-row"><strong>Cluster sémantique VPN</strong><span className="amber">+11,2 %</span><span className="muted">écart 24 h</span></div><div className="source-row"><strong>Répartition des priorités</strong><span className="green">+2,1 %</span><span className="muted">stable</span></div></GlassCard>
        <GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined blue">account_tree</span>Facteurs influents</h3></div>{[["Minutes SLA restantes",91],["Backlog du groupe",78],["Nombre de réaffectations",62],["Complexité sémantique",49]].map(([n,v])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className="blue">{v}</span></div><Progress value={Number(v)} tone="blue"/></div>)}</GlassCard>
      </div>
    </AppShell>
  );
}
