import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, PrimaryButton, Progress } from "../../../components/UI";

const subnav = [{ label: "Intelligence ticket", href: "/service-ops" },{ label: "Charge & capacité", href: "/service-ops/workload", active: true },{ label: "Connaissances", href: "/service-ops/knowledge" },{ label: "Actions IA", href: "/service-ops/actions" }];

export default function WorkloadPage() {
  const heatRows = [["Support N1",[2,2,3,3,4,4,3,3,2,2,2,1]],["Réseau",[1,1,2,2,2,3,4,4,3,2,2,1]],["Workplace",[1,2,2,3,3,3,3,2,2,2,1,1]],["Sécurité",[2,2,3,4,4,4,4,4,3,3,2,2]]] as const;
  return (<AppShell section="service" subnav={subnav} searchPlaceholder="Rechercher une équipe ou une file..."><PageIntro eyebrow={<span className="eyebrow tone-green">Pilotage de capacité</span>} title="Charge & capacité" subtitle="Anticiper la saturation des équipes, rééquilibrer les files et protéger les SLA." action={<PrimaryButton><span className="material-symbols-outlined">auto_fix_high</span>Simuler un rééquilibrage</PrimaryButton>} /><div className="dashboard-grid">
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Charge globale</span><span className="material-symbols-outlined amber">speed</span></div><div className="metric-value amber">78 %</div><div className="metric-note">+11 % VS CHARGE HABITUELLE</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Équipes en surcharge</span><span className="material-symbols-outlined red">group_off</span></div><div className="metric-value red">2</div><div className="metric-note">SUPPORT N1 · SÉCURITÉ</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Pic prévu</span><span className="material-symbols-outlined blue">schedule</span></div><div className="metric-value blue">16:20</div><div className="metric-note">CHARGE ATTENDUE : 91 %</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Gain du rééquilibrage</span><span className="material-symbols-outlined green">trending_up</span></div><div className="metric-value green">+14 %</div><div className="metric-note">CONFORMITÉ SLA ESTIMÉE</div></GlassCard>
    <GlassCard className="card-pad span-8"><div className="card-header"><h3><span className="material-symbols-outlined green">grid_view</span>Carte de charge</h3><Chip tone="muted">12 prochaines heures</Chip></div><div className="heatmap"><span />{Array.from({length:12},(_,i)=><span className="heat-label" key={i}>{String(i+9).padStart(2,"0")}h</span>)}{heatRows.flatMap(([name,vals])=>[<span className="heat-label" key={String(name)}>{String(name)}</span>,...vals.map((v,i)=><span className={`heat h${v}`} key={`${name}-${i}`}/>)])}</div></GlassCard>
    <GlassCard className="card-pad span-4"><div className="card-header"><h3><span className="material-symbols-outlined amber">priority_high</span>Files sous tension</h3></div>{[["Support N1",92,"amber"],["Sécurité",98,"red"],["Architecture Cloud",68,"blue"],["Réseau",45,"green"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "amber"|"red"|"blue"|"green"}/></div>)}</GlassCard>
    <GlassCard className="card-pad span-12"><div className="card-header"><h3><span className="material-symbols-outlined green">move_up</span>Recommandations de rééquilibrage</h3><Chip tone="green">3 actions recommandées</Chip></div><div className="table-head cols-5"><span>Recommandation</span><span>Depuis</span><span>Vers</span><span>Impact</span><span>Confiance</span></div>{[["Déplacer 14 tickets de réinitialisation de mot de passe","Support N1","Workplace","-11 % de charge","94 %"],["Router 6 tickets IAM","Support N1","Sécurité N2","-4 risques SLA","89 %"],["Différer 21 tâches batch à faible risque","Sécurité","File asynchrone","+38 min de marge","86 %"]].map(r=><div className="table-row cols-5" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className="green">{r[2]}</span><span>{r[3]}</span><span className="blue">{r[4]}</span></div>)}</GlassCard>
  </div></AppShell>);
}
