import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, PrimaryButton, Progress } from "../../../components/UI";

const subnav = [{ label: "Ticket Intelligence", href: "/service-ops" },{ label: "Workload & Capacity", href: "/service-ops/workload", active: true },{ label: "Knowledge", href: "/service-ops/knowledge" },{ label: "AI Actions", href: "/service-ops/actions" }];
export default function WorkloadPage() {
  const heatRows = [["L1 Support",[2,2,3,3,4,4,3,3,2,2,2,1]],["Network",[1,1,2,2,2,3,4,4,3,2,2,1]],["Workplace",[1,2,2,3,3,3,3,2,2,2,1,1]],["SecOps",[2,2,3,4,4,4,4,4,3,3,2,2]]] as const;
  return (<AppShell section="service" subnav={subnav} searchPlaceholder="Search team or queue..."><PageIntro eyebrow={<span className="eyebrow tone-green">Capacity Intelligence</span>} title="Workload & Capacity" subtitle="Forecast pressure, rebalance queues and protect SLA before teams saturate." action={<PrimaryButton><span className="material-symbols-outlined">auto_fix_high</span>Simulate Rebalance</PrimaryButton>} /><div className="dashboard-grid">
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Global Load</span><span className="material-symbols-outlined amber">speed</span></div><div className="metric-value amber">78%</div><div className="metric-note">+11% VS NORMAL BASELINE</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Overloaded Teams</span><span className="material-symbols-outlined red">group_off</span></div><div className="metric-value red">2</div><div className="metric-note">L1 SUPPORT · SECOPS</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Forecast Peak</span><span className="material-symbols-outlined blue">schedule</span></div><div className="metric-value blue">16:20</div><div className="metric-note">EXPECTED 91% LOAD</div></GlassCard>
    <GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Rebalance Gain</span><span className="material-symbols-outlined green">trending_up</span></div><div className="metric-value green">+14%</div><div className="metric-note">PROJECTED SLA COMPLIANCE</div></GlassCard>
    <GlassCard className="card-pad span-8"><div className="card-header"><h3><span className="material-symbols-outlined green">grid_view</span>Capacity Heatmap</h3><Chip tone="muted">Next 12 Hours</Chip></div><div className="heatmap"><span />{Array.from({length:12},(_,i)=><span className="heat-label" key={i}>{String(i+9).padStart(2,"0")}h</span>)}{heatRows.flatMap(([name,vals])=>[<span className="heat-label" key={String(name)}>{String(name)}</span>,...vals.map((v,i)=><span className={`heat h${v}`} key={`${name}-${i}`}/>)])}</div></GlassCard>
    <GlassCard className="card-pad span-4"><div className="card-header"><h3><span className="material-symbols-outlined amber">priority_high</span>Queue Hotspots</h3></div>{[["L1 Support",92,"amber"],["SecOps",98,"red"],["Cloud Architecture",68,"blue"],["Network Ops",45,"green"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "amber"|"red"|"blue"|"green"}/></div>)}</GlassCard>
    <GlassCard className="card-pad span-12"><div className="card-header"><h3><span className="material-symbols-outlined green">move_up</span>AI Rebalancing Recommendations</h3><Chip tone="green">3 Safe Moves</Chip></div><div className="table-head cols-5"><span>Recommendation</span><span>From</span><span>To</span><span>Impact</span><span>Confidence</span></div>{[["Move 14 password-reset tickets","L1 Support","Workplace","-11% load","94%"],["Route 6 IAM tickets","L1 Support","SecOps N2","-4 SLA risks","89%"],["Defer 21 low-risk batch tasks","SecOps","Async Queue","+38 min buffer","86%"]].map(r=><div className="table-row cols-5" key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><span className="green">{r[2]}</span><span>{r[3]}</span><span className="blue">{r[4]}</span></div>)}</GlassCard>
  </div></AppShell>);
}
