export type DemoView = {
  id: string;
  label: string;
};

export type DemoAsset = {
  name: string;
  serial: string;
  warranty: string;
  incidentCount: number;
};

export type DemoTicket = {
  id: string;
  subject: string;
  requester: string;
  requesterEmail: string;
  status: string;
  priority: "Faible" | "Moyenne" | "Élevée" | "Urgente";
  source: "IA" | "Email" | "Portail" | "Téléphone";
  type: "Incident" | "Demande de service" | "Incident majeur";
  urgency: "Faible" | "Moyen" | "Élevé";
  impact: "Faible" | "Moyen" | "Élevé";
  group: string;
  agent: string;
  category: string;
  subcategory: string;
  item: string;
  location: "Rouen" | "Belfort" | "Siège";
  vip: boolean;
  createdAt: string;
  slaRisk: number;
  description: string;
  conversation: string;
  tags: string[];
  asset?: DemoAsset;
};

export const DEMO_VIEWS: DemoView[] = [
  { id: "52000164396", label: "Equipe Régulation" },
  { id: "52000165516", label: "Demande de nouveaux PC Tous" },
  { id: "52000167456", label: "Remplacement de PC" },
  { id: "52000174292", label: "Accueil des employés" },
  { id: "52000174344", label: "Tickets non assignés" },
  { id: "52000178023", label: "Tickets dû aujourd'hui - Périmètre D'CLIC" },
  { id: "52000181147", label: "Douchettes SATO TSC" },
  { id: "52000182277", label: "Création de compte" },
  { id: "52000188443", label: "Consommables" },
  { id: "52000190704", label: "Demande d'écrans à envoyer" },
  { id: "52000192492", label: "TicketsDclic à traiter" },
  { id: "52000203359", label: "Tickets Métier" },
  { id: "52000210081", label: "Mes tickets" },
  { id: "52000212015", label: "IT Incidents" },
  { id: "52000212016", label: "Service Requests" },
  { id: "52000213529", label: "Demande de nouveaux PC (Mis au plot)" },
  { id: "52000216300", label: "Consommables bureautique TOUS" },
  { id: "52000216494", label: "Demande de nouveaux PC A Suivre" },
  { id: "52000216635", label: "Tous les dossiers demandeurs VIP" },
  { id: "52000216816", label: "Dossiers VIP - SD" },
  { id: "52000216818", label: "Imprimantes Niveau 1" },
  { id: "52000217061", label: "Tous les dossiers Prep PC demandeurs VIP" },
  { id: "52000217134", label: "Demande de nouveaux PC (Mis au plot) URGENT" },
  { id: "52000224366", label: "Plot Tibco imprimantes" },
  { id: "52000225782", label: "Le demandeur a répondu" },
  { id: "52000225856", label: "Tickets que je surveille" },
  { id: "52000226712", label: "Assignation des tickets" },
  { id: "52000228979", label: "Incident(s) Majeur(s) en cours" },
  { id: "52000229010", label: "Répartitions des demandes ouvertes - Périmètre D'CLIC" },
  { id: "52000229061", label: "Historique des incidents majeurs" },
  { id: "52000229460", label: "My Team Major Incidents" },
  { id: "52000229976", label: "Enquête négative" },
  { id: "52000230464", label: "Installation Logiciels et Gestion des licences" },
  { id: "52000230465", label: "Wyse" },
  { id: "52000230466", label: "Demande de nouvelles imprimantes" },
  { id: "52000230467", label: "Consommables SME" },
  { id: "52000230551", label: "Demandes au siège (Support de proximité)" },
  { id: "52000230693", label: "Consommables bureautique (Stock à vérifier)" },
  { id: "52000230694", label: "Consommables bureautique (A Traiter)" },
  { id: "52000230695", label: "Consommables bureautique (Commande à passer)" },
  { id: "52000230696", label: "Consommables bureautique (En cours de commande)" },
  { id: "52000230924", label: "Tickets imprimantes" },
  { id: "52000233604", label: "Tickets créés par l'IA" },
  { id: "52000235284", label: "Remplacement de PC - 1ere Relance" },
  { id: "52000235285", label: "Remplacement de PC - 2eme Relance" },
  { id: "52000235286", label: "Remplacement de PC - Sans Personnalisation" },
  { id: "52000236515", label: "My Team Status Page Incidents" },
  { id: "52000238150", label: "Tickets IA - Aujourd'hui" },
  { id: "52000240503", label: "Création de comptes - Ouvert" },
  { id: "52000240504", label: "Création de comptes - En attente" },
  { id: "52000240507", label: "Demandes Outlook" },
  { id: "52000240513", label: "Sortie de Papiers" },
  { id: "52000240614", label: "Demandes D'CLIC - Statut Ouvert" },
  { id: "52000241051", label: "Tous les dossiers En attente d'approbation" },
  { id: "52000241528", label: "Demandes de service Sans Balise" },
  { id: "52000241643", label: "Installation de nouvelles imprimantes" },
  { id: "52000241670", label: "Historique des tickets IA" },
  { id: "52000241710", label: "Copie de Création de comptes - Ouvert" },
  { id: "52000241711", label: "Création de comptes - A traiter et non assigné" },
  { id: "52000249717", label: "Tickets M3 Niveau 1 SD" },
  { id: "52000252732", label: "Remplacement de PC - A récupérer" },
  { id: "52000252733", label: "Remplacement de PC - Récupéré" },
  { id: "52000256704", label: "Tous les incidents majeurs" },
  { id: "52000257155", label: "Tickets SME/FastMoving" },
  { id: "52000261052", label: "Équipe Métier Exploitation" },
  { id: "52000267720", label: "Budget 2025" },
  { id: "52000268316", label: "Incidents Métier NPI" },
  { id: "52000268317", label: "Demandes Métier NPI" },
  { id: "52000268455", label: "Enquêtes négatives traitées" },
  { id: "52000270185", label: "Suivi des SR pour la DC" },
  { id: "52000277874", label: "Incidents NPI non assignés" },
  { id: "52000279256", label: "Enquête de satisfaction" },
  { id: "52000281104", label: "PC vente - Modèle Latitude 5400" },
  { id: "52000281105", label: "PC vente - Modèle Latitude 5500" },
  { id: "52000281106", label: "PC vente - Modèle Latitude 7400" },
  { id: "52000281107", label: "PC vente - Modèle Latitude 7490" },
  { id: "52000282820", label: "Renouvellement XEROX" },
  { id: "52000285663", label: "Groupe Demandeurs Commerce - SR" },
  { id: "52000288081", label: "Mes tickets Belfort - TEST" },
  { id: "52000288085", label: "Mes demandes" },
  { id: "52000288227", label: "Vue test - Mes tickets" },
  { id: "52000288584", label: "Incidents Métier Supply - Belfort" },
  { id: "52000288585", label: "Demandes Métier NPI - Belfort" },
  { id: "52000288586", label: "Incidents Supply Chain non assignés - Belfort" },
  { id: "52000289501", label: "Mes Tickets TEST" },
  { id: "52000289502", label: "Les tickets de mes groupes de traitement TEST" },
  { id: "52000290041", label: "Tickets NOLAN" },
  { id: "52000290096", label: "Tickets en attente Supply niveau 2 métier" },
  { id: "52000290216", label: "Incidents Métier NPI du jour - Belfort" },
  { id: "52000290218", label: "Incidents Métier NPI du jour - Rouen" },
  { id: "52000291345", label: "Tous tickets BELFORT" },
  { id: "52000292098", label: "Supervision Tickets VIP Hors SD" },
  { id: "52000292099", label: "Supervision Tickets VIP - SD" },
  { id: "52000297728", label: "incidents" },
  { id: "52000299316", label: "Tickets commerce à traiter" },
  { id: "new_and_my_open", label: "Mes Tickets ouverts & nouveaux" },
  { id: "ml_predicted", label: "Tickets avec suggestions de champ" },
  { id: "unresolved", label: "Tous les Tickets non résolus" },
  { id: "all_tickets", label: "Tous les Tickets" },
  { id: "monitored_by", label: "Tickets que je surveille" },
  { id: "spam", label: "Spam" },
  { id: "deleted", label: "Corbeille" },
  { id: "requested_by_me", label: "Tickets que j'ai demandés" },
  { id: "ticket_shared_with_me", label: "Partagé avec moi" },
  { id: "can_respond_to", label: "Tickets auxquels je peux répondre" },
];

export const DEMO_TICKETS: DemoTicket[] = [
  {
    id: "INC-157104",
    subject: "Re: Opportunité de partenariat - A-Line Brasil Cosmetics",
    requester: "Rodrigo.souto",
    requesterEmail: "rodrigo.souto@alinegroup.com.br",
    status: "Ouvert",
    priority: "Faible",
    source: "IA",
    type: "Incident",
    urgency: "Moyen",
    impact: "Faible",
    group: "Sécurité Niveau 2 RSSI",
    agent: "--",
    category: "Sécurité",
    subcategory: "Mails douteux",
    item: "--",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-12T19:38:00+02:00",
    slaRisk: 39,
    description: "De : rodrigo.souto@alinegroup.com.br\nObjet : Re: Opportunité de partenariat - A-Line Brasil Cosmetics | Solutions capillaires et soins des cils & sourcils\nJe me permets de vous contacter afin de vous présenter A-Line Brasil Cosmetics, une marque brésilienne spécialisée dans le développement de solutions dermocosmétiques dédiées aux soins capillaires ainsi qu’aux cils et sourcils.",
    conversation: "Message externe transféré à la DSI pour vérification. Aucun clic ou ouverture de pièce jointe n'est documenté dans le ticket.",
    tags: ["mail-douteux", "externe", "ia"],
  },
  {
    id: "INC-157132",
    subject: "Outlook ne démarre plus depuis la mise à jour",
    requester: "Amandine Leroux",
    requesterEmail: "amandine.leroux@cerp.local",
    status: "Ouvert",
    priority: "Élevée",
    source: "Portail",
    type: "Incident",
    urgency: "Élevé",
    impact: "Moyen",
    group: "Service Desk N1",
    agent: "Nolan",
    category: "Messagerie",
    subcategory: "Outlook",
    item: "Client lourd",
    location: "Rouen",
    vip: true,
    createdAt: "2026-08-13T08:04:00+02:00",
    slaRisk: 84,
    description: "Outlook affiche une fenêtre blanche puis se ferme depuis la mise à jour de ce matin. Je ne peux plus accéder à mes mails.",
    conversation: "Le demandeur confirme un redémarrage du poste sans amélioration.",
    tags: ["outlook", "vip"],
    asset: { name: "Dell Latitude 5420", serial: "PC-84391", warranty: "18/04/2027", incidentCount: 4 },
  },
  {
    id: "SR-156383",
    subject: "Remplacement de PC décidé par la DSI : Demande Amélie Ginguené",
    requester: "Amélie Ginguené",
    requesterEmail: "amelie.ginguene@cerp.local",
    status: "Préparation de PC en cours",
    priority: "Élevée",
    source: "Portail",
    type: "Demande de service",
    urgency: "Moyen",
    impact: "Faible",
    group: "Workplace",
    agent: "Sylvain",
    category: "Poste de travail",
    subcategory: "Remplacement PC",
    item: "Préparation",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-11T11:00:00+02:00",
    slaRisk: 55,
    description: "Remplacement du poste utilisateur décidé dans le cadre du renouvellement du parc.",
    conversation: "Fiche de préparation partiellement complétée.",
    tags: ["remplacement-pc"],
    asset: { name: "Dell Latitude 5400", serial: "PC-55220", warranty: "Expirée", incidentCount: 6 },
  },
  {
    id: "SR-132122",
    subject: "Création de compte pour nouvel arrivant - Commerce",
    requester: "Marie Duval",
    requesterEmail: "marie.duval@cerp.local",
    status: "En attente",
    priority: "Moyenne",
    source: "Portail",
    type: "Demande de service",
    urgency: "Moyen",
    impact: "Moyen",
    group: "IAM",
    agent: "--",
    category: "Identité & accès",
    subcategory: "Création de compte",
    item: "Nouveau collaborateur",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-10T14:20:00+02:00",
    slaRisk: 72,
    description: "Merci de créer les accès du nouvel arrivant pour lundi prochain.",
    conversation: "Le manager n'a pas encore renseigné le périmètre applicatif.",
    tags: ["compte", "onboarding"],
  },
  {
    id: "INC-157020",
    subject: "Imprimante logistique indisponible - zone préparation",
    requester: "Accueil Logistique",
    requesterEmail: "accueil.logistique@cerp.local",
    status: "Ouvert",
    priority: "Urgente",
    source: "Téléphone",
    type: "Incident majeur",
    urgency: "Élevé",
    impact: "Élevé",
    group: "Support Imprimantes N1",
    agent: "Claire",
    category: "Impression",
    subcategory: "Imprimante",
    item: "Production",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-13T07:42:00+02:00",
    slaRisk: 92,
    description: "L'imprimante de la zone préparation ne sort plus les étiquettes et bloque la préparation des commandes.",
    conversation: "Plusieurs équipes indiquent le même blocage depuis 07:35.",
    tags: ["imprimante", "production", "majeur"],
    asset: { name: "Zebra ZT411 PREP-01", serial: "IMP-0091", warranty: "12/01/2027", incidentCount: 9 },
  },
  {
    id: "INC-156991",
    subject: "VPN impossible après changement de mot de passe",
    requester: "Paul Meyer",
    requesterEmail: "paul.meyer@cerp.local",
    status: "Ouvert",
    priority: "Élevée",
    source: "Email",
    type: "Incident",
    urgency: "Élevé",
    impact: "Faible",
    group: "Réseau N2",
    agent: "Karim",
    category: "Réseau",
    subcategory: "VPN",
    item: "Authentification",
    location: "Belfort",
    vip: false,
    createdAt: "2026-08-12T09:15:00+02:00",
    slaRisk: 78,
    description: "Depuis mon changement de mot de passe le VPN refuse la connexion. Message : credentials rejected.",
    conversation: "Le compte fonctionne sur Microsoft 365.",
    tags: ["vpn", "authentification"],
  },
  {
    id: "SR-157005",
    subject: "Installation Visio pour projet Supply",
    requester: "Luc Bernard",
    requesterEmail: "luc.bernard@cerp.local",
    status: "En attente d'approbation",
    priority: "Faible",
    source: "Portail",
    type: "Demande de service",
    urgency: "Faible",
    impact: "Faible",
    group: "Logiciels & Licences",
    agent: "Eva",
    category: "Logiciels & licences",
    subcategory: "Installation logiciel",
    item: "Visio",
    location: "Belfort",
    vip: false,
    createdAt: "2026-08-09T10:30:00+02:00",
    slaRisk: 18,
    description: "Besoin de Visio pour cartographier les flux du projet Supply.",
    conversation: "Demande transmise au responsable budgétaire.",
    tags: ["visio", "licence"],
  },
  {
    id: "INC-156870",
    subject: "Erreur M3 lors de la validation d'une commande",
    requester: "Sophie Martin",
    requesterEmail: "sophie.martin@cerp.local",
    status: "En attente de réponse de l'utilisateur",
    priority: "Moyenne",
    source: "IA",
    type: "Incident",
    urgency: "Moyen",
    impact: "Moyen",
    group: "M3 Niveau 1 SD",
    agent: "--",
    category: "Application métier",
    subcategory: "M3",
    item: "Validation commande",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-08T16:10:00+02:00",
    slaRisk: 66,
    description: "M3 affiche ERREUR 501 quand je valide la commande 893222.",
    conversation: "Une capture d'écran a été demandée.",
    tags: ["m3", "ia"],
  },
  {
    id: "INC-156812",
    subject: "Incident NPI - synchronisation catalogue",
    requester: "Equipe NPI",
    requesterEmail: "npi@cerp.local",
    status: "Ouvert",
    priority: "Élevée",
    source: "Portail",
    type: "Incident",
    urgency: "Élevé",
    impact: "Moyen",
    group: "Métier NPI",
    agent: "Marc",
    category: "NPI",
    subcategory: "Synchronisation",
    item: "Catalogue",
    location: "Belfort",
    vip: false,
    createdAt: "2026-08-07T13:25:00+02:00",
    slaRisk: 75,
    description: "La synchronisation du catalogue NPI ne remonte plus les nouveaux articles.",
    conversation: "Le flux de 12:00 est incomplet.",
    tags: ["npi", "catalogue"],
  },
  {
    id: "INC-156740",
    subject: "Demandeur VIP - lenteurs poste de travail",
    requester: "Direction Commerciale",
    requesterEmail: "direction.commerce@cerp.local",
    status: "Ouvert",
    priority: "Urgente",
    source: "Téléphone",
    type: "Incident",
    urgency: "Élevé",
    impact: "Moyen",
    group: "Support de proximité",
    agent: "Julien",
    category: "Poste de travail",
    subcategory: "Performance",
    item: "Windows",
    location: "Siège",
    vip: true,
    createdAt: "2026-08-13T08:20:00+02:00",
    slaRisk: 88,
    description: "Le poste est extrêmement lent depuis ce matin, toutes les applications mettent plusieurs minutes à s'ouvrir.",
    conversation: "Utilisateur VIP avec réunion de direction à 10:00.",
    tags: ["vip", "performance"],
    asset: { name: "Dell Latitude 7400", serial: "PC-74001", warranty: "03/11/2026", incidentCount: 5 },
  },
  {
    id: "SR-156650",
    subject: "Consommables bureautique - toner noir",
    requester: "Agence Rouen",
    requesterEmail: "agence.rouen@cerp.local",
    status: "Commande à passer",
    priority: "Faible",
    source: "Portail",
    type: "Demande de service",
    urgency: "Faible",
    impact: "Faible",
    group: "Services généraux",
    agent: "Aline",
    category: "Consommables",
    subcategory: "Bureautique",
    item: "Toner",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-06T09:00:00+02:00",
    slaRisk: 12,
    description: "Besoin de deux toners noirs pour l'imprimante de l'accueil.",
    conversation: "Stock local vérifié : 0 unité.",
    tags: ["consommables", "toner"],
  },
  {
    id: "INC-156603",
    subject: "Sortie de papiers intempestive sur imprimante",
    requester: "Pharmacie Centrale",
    requesterEmail: "pharmacie.centrale@cerp.local",
    status: "Ouvert",
    priority: "Moyenne",
    source: "Email",
    type: "Incident",
    urgency: "Moyen",
    impact: "Faible",
    group: "Support Imprimantes N1",
    agent: "--",
    category: "Impression",
    subcategory: "Sortie papier",
    item: "Bac papier",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-05T15:40:00+02:00",
    slaRisk: 61,
    description: "L'imprimante lance des feuilles blanches de manière aléatoire.",
    conversation: "Aucun changement de pilote connu.",
    tags: ["imprimante", "papier"],
  },
  {
    id: "INC-156550",
    subject: "Supply Chain - blocage interface Belfort",
    requester: "Supply Belfort",
    requesterEmail: "supply.belfort@cerp.local",
    status: "En attente",
    priority: "Élevée",
    source: "Portail",
    type: "Incident",
    urgency: "Élevé",
    impact: "Élevé",
    group: "Supply Niveau 2 métier",
    agent: "--",
    category: "Supply Chain",
    subcategory: "Interface",
    item: "Flux",
    location: "Belfort",
    vip: false,
    createdAt: "2026-08-04T11:25:00+02:00",
    slaRisk: 81,
    description: "L'interface Supply n'affiche plus les mouvements après 10h45.",
    conversation: "Plusieurs utilisateurs Belfort concernés.",
    tags: ["supply", "belfort"],
  },
  {
    id: "SR-156499",
    subject: "Nouvelle imprimante pour l'équipe commerce",
    requester: "Commerce",
    requesterEmail: "commerce@cerp.local",
    status: "Ouvert",
    priority: "Faible",
    source: "Portail",
    type: "Demande de service",
    urgency: "Faible",
    impact: "Faible",
    group: "Workplace",
    agent: "Sarah",
    category: "Impression",
    subcategory: "Nouvelle imprimante",
    item: "Installation",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-03T10:00:00+02:00",
    slaRisk: 15,
    description: "Demande d'une nouvelle imprimante réseau pour le plateau commerce.",
    conversation: "Validation budgétaire obtenue.",
    tags: ["imprimante", "commerce"],
  },
  {
    id: "INC-156420",
    subject: "Enquête négative - délai de résolution",
    requester: "Client interne",
    requesterEmail: "client.interne@cerp.local",
    status: "Ouvert",
    priority: "Moyenne",
    source: "IA",
    type: "Incident",
    urgency: "Moyen",
    impact: "Faible",
    group: "Qualité Service Desk",
    agent: "Léa",
    category: "Qualité",
    subcategory: "Satisfaction",
    item: "Enquête négative",
    location: "Rouen",
    vip: false,
    createdAt: "2026-08-02T17:05:00+02:00",
    slaRisk: 40,
    description: "Retour négatif suite à un délai de résolution jugé trop long.",
    conversation: "Note CSAT 1/5.",
    tags: ["csat", "ia"],
  },
];

export function normalizeText(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[’']/g, " ")
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function filterTicketsForView(viewLabel: string, tickets: DemoTicket[]): DemoTicket[] {
  const label = normalizeText(viewLabel);
  const has = (ticket: DemoTicket, term: string) => normalizeText(`${ticket.subject} ${ticket.category} ${ticket.subcategory} ${ticket.group} ${ticket.tags.join(" ")}`).includes(term);

  if (label.includes("non assigne")) return tickets.filter((ticket) => ticket.agent === "--");
  if (label.includes("vip")) return tickets.filter((ticket) => ticket.vip);
  if (label.includes("remplacement de pc") || label.includes("nouveaux pc") || label.includes("prep pc") || label.includes("pc vente")) return tickets.filter((ticket) => has(ticket, "pc") || has(ticket, "poste de travail"));
  if (label.includes("imprim") || label.includes("xerox") || label.includes("sortie de papiers") || label.includes("sato") || label.includes("tsc")) return tickets.filter((ticket) => has(ticket, "imprim") || has(ticket, "papier"));
  if (label.includes("creation de compte") || label.includes("creation de comptes")) return tickets.filter((ticket) => has(ticket, "compte"));
  if (label.includes("outlook")) return tickets.filter((ticket) => has(ticket, "outlook"));
  if (label.includes("consommable")) return tickets.filter((ticket) => has(ticket, "consommable"));
  if (label.includes("npi")) return tickets.filter((ticket) => has(ticket, "npi"));
  if (label.includes("supply")) return tickets.filter((ticket) => has(ticket, "supply"));
  if (label.includes("commerce")) return tickets.filter((ticket) => has(ticket, "commerce"));
  if (label.includes("belfort")) return tickets.filter((ticket) => ticket.location === "Belfort");
  if (label.includes("rouen")) return tickets.filter((ticket) => ticket.location === "Rouen");
  if (label.includes("ia")) return tickets.filter((ticket) => ticket.source === "IA");
  if (label.includes("incident majeur")) return tickets.filter((ticket) => ticket.type === "Incident majeur");
  if (label.includes("service request") || label.includes("demande de service") || label.includes("sr ")) return tickets.filter((ticket) => ticket.type === "Demande de service");
  if (label.includes("incident")) return tickets.filter((ticket) => ticket.type === "Incident" || ticket.type === "Incident majeur");
  if (label.includes("attente")) return tickets.filter((ticket) => normalizeText(ticket.status).includes("attente"));
  if (label.includes("ouvert")) return tickets.filter((ticket) => ticket.status === "Ouvert");
  if (label.includes("tous les tickets") || label.includes("tous tickets")) return tickets;

  return tickets;
}
