import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, Progress } from "../../../components/UI";

const subnav=[{label:"API & quotas",href:"/system-config"},{label:"Audit & gouvernance",href:"/system-config/audit",active:true}];

export default function AuditPage(){return <AppShell section="system" title="Audit & gouvernance" subnav={subnav} searchPlaceholder="Rechercher un événement d’audit..."><PageIntro eyebrow={<span className="eyebrow tone-green">Contrôle & traçabilité</span>} title="Traçabilité des décisions" subtitle="Reconstituer qui a proposé, validé, exécuté et vérifié chaque action assistée par l’IA."/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Actions auditées</span><span className="material-symbols-outlined green">fact_check</span></div><div className="metric-value">12 482</div><div className="metric-note">100 % DES ÉCRITURES COUVERTES</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Actions bloquées par politique</span><span className="material-symbols-outlined red">block</span></div><div className="metric-value red">38</div><div className="metric-note">30 DERNIERS JOURS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Validations humaines</span><span className="material-symbols-outlined amber">person_check</span></div><div className="metric-value amber">417</div><div className="metric-note">RISQUE MOYEN / ÉLEVÉ</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Complétude de la traçabilité</span><span className="material-symbols-outlined blue">account_tree</span></div><div className="metric-value blue">99,9 %</div><div className="metric-note">COUVERTURE CORRELATION ID</div></GlassCard>
<GlassCard className="table-card span-12"><div className="card-pad"><div className="card-header"><h3><span className="material-symbols-outlined green">history</span>Événements gouvernés récents</h3><Chip tone="green">Journal immuable</Chip></div></div><div className="table-head cols-6"><span>Heure / événement</span><span>Acteur</span><span>Ressource</span><span>Politique</span><span>Décision</span><span>Corrélation</span></div>{[["14:24:18 · command.verified","manager.jl","INC-9942","P-HITL-001","Vérifié","corr-8a41"],["14:24:16 · approval.granted","manager.jl","INC-9942","P-HITL-001","Validé","corr-8a41"],["14:23:07 · policy.evaluated","dclic-ai","INC-9942","P-HITL-001","Validation requise","corr-8a41"],["14:19:32 · action.denied","dclic-ai","AST-442","P-BLOCK-001","Refusé","corr-12bc"],["14:15:02 · command.verified","agent.md","INC-9920","P-L3-TAG","Vérifié","corr-117e"]].map(r=><div className="table-row cols-6" key={r[0]}><strong>{r[0]}</strong><code>{r[1]}</code><span>{r[2]}</span><code>{r[3]}</code><Chip tone={r[4]==="Refusé"?"red":r[4]==="Validation requise"?"amber":"green"}>{r[4]}</Chip><code className="muted">{r[5]}</code></div>)}</GlassCard>
<GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined amber">policy</span>Décisions de politique</h3></div>{[["Autoriser",78,"green"],["Validation requise",18,"amber"],["Refuser",4,"red"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "green"|"amber"|"red"}/></div>)}<div className="action-card"><span className="card-label">Règle de sécurité</span><p>La confiance ne donne jamais une autorisation. La décision d’accès reste déterministe et indépendante du modèle.</p></div></GlassCard>
<GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined blue">fingerprint</span>Chaîne de preuve</h3></div><div className="timeline"><div className="timeline-item"><h4>État observé</h4><p>Snapshot du ticket, horloge SLA et charge du groupe référencés par des identifiants traçables.</p></div><div className="timeline-item"><h4>Décision du modèle</h4><p>Nom du modèle, version, confiance et contenu de la recommandation enregistrés.</p></div><div className="timeline-item"><h4>Décision humaine / politique</h4><p>L’approbateur et la règle de politique sont stockés séparément de la couche de raisonnement IA.</p></div><div className="timeline-item"><h4>Preuve d’exécution</h4><p>Réponse Freshservice et vérification par relecture reliées au même identifiant de corrélation.</p></div></div></GlassCard>
</div></AppShell>}
