import { AppShell } from "../../../components/AppShell";
import { Chip, GlassCard, PageIntro, Progress } from "../../../components/UI";
const subnav=[{label:"API & Quota",href:"/system-config"},{label:"Audit & Governance",href:"/system-config/audit",active:true}];
export default function AuditPage(){return <AppShell section="system" title="Audit & Governance" subnav={subnav} searchPlaceholder="Search audit event..."><PageIntro eyebrow={<span className="eyebrow tone-green">Control & Accountability</span>} title="Immutable Decision Trail" subtitle="Reconstruct who proposed, approved, executed and verified every AI-assisted action."/><div className="dashboard-grid">
<GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Audited Actions</span><span className="material-symbols-outlined green">fact_check</span></div><div className="metric-value">12,482</div><div className="metric-note">100% WRITE COVERAGE</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Policy Denials</span><span className="material-symbols-outlined red">block</span></div><div className="metric-value red">38</div><div className="metric-note">LAST 30 DAYS</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Human Approvals</span><span className="material-symbols-outlined amber">person_check</span></div><div className="metric-value amber">417</div><div className="metric-note">MEDIUM/HIGH RISK</div></GlassCard><GlassCard className="metric-card span-3"><div className="metric-top"><span className="card-label">Trace Completeness</span><span className="material-symbols-outlined blue">account_tree</span></div><div className="metric-value blue">99.9%</div><div className="metric-note">CORRELATION ID COVERAGE</div></GlassCard>
<GlassCard className="table-card span-12"><div className="card-pad"><div className="card-header"><h3><span className="material-symbols-outlined green">history</span>Recent Governed Events</h3><Chip tone="green">Immutable Log</Chip></div></div><div className="table-head cols-6"><span>Time / Event</span><span>Actor</span><span>Resource</span><span>Policy</span><span>Decision</span><span>Correlation</span></div>{[["14:24:18 · command.verified","manager.jl","INC-9942","P-HITL-001","Verified","corr-8a41"],["14:24:16 · approval.granted","manager.jl","INC-9942","P-HITL-001","Approved","corr-8a41"],["14:23:07 · policy.evaluated","dclic-ai","INC-9942","P-HITL-001","Approval","corr-8a41"],["14:19:32 · action.denied","dclic-ai","AST-442","P-BLOCK-001","Denied","corr-12bc"],["14:15:02 · command.verified","agent.md","INC-9920","P-L3-TAG","Verified","corr-117e"]].map(r=><div className="table-row cols-6" key={r[0]}><strong>{r[0]}</strong><code>{r[1]}</code><span>{r[2]}</span><code>{r[3]}</code><Chip tone={r[4]==="Denied"?"red":r[4]==="Approval"?"amber":"green"}>{r[4]}</Chip><code className="muted">{r[5]}</code></div>)}</GlassCard>
<GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined amber">policy</span>Policy Outcomes</h3></div>{[["Allow",78,"green"],["Require Approval",18,"amber"],["Deny",4,"red"]].map(([n,v,t])=><div className="work-row" key={String(n)}><div className="work-row-head"><span>{n}</span><span className={String(t)}>{v}%</span></div><Progress value={Number(v)} tone={t as "green"|"amber"|"red"}/></div>)}<div className="action-card"><span className="card-label">Safety Rule</span><p>Confidence never grants permission. Authorization remains deterministic and independent from the model.</p></div></GlassCard>
<GlassCard className="card-pad span-6"><div className="card-header"><h3><span className="material-symbols-outlined blue">fingerprint</span>Evidence Chain</h3></div><div className="timeline"><div className="timeline-item"><h4>Observed state</h4><p>Ticket snapshot, SLA clock and group workload referenced by immutable identifiers.</p></div><div className="timeline-item"><h4>Model decision</h4><p>Model name, version, confidence and recommendation payload captured.</p></div><div className="timeline-item"><h4>Human / policy decision</h4><p>Approver and policy rule stored separately from the LLM reasoning layer.</p></div><div className="timeline-item"><h4>Execution proof</h4><p>Freshservice response plus read-after-write verification linked to the same correlation ID.</p></div></div></GlassCard>
</div></AppShell>}
